[build]
publish = "public"
command = "hugo --gc"

[context.production]

[context.production.environment]
HUGO_VERSION = "0.108.0"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --buildFuture"

[context.deploy-preview.environment]
HUGO_VERSION = "0.108.0"
HUGO_ENV = "production"

[context.branch-deploy]
command = "hugo --gc --buildFuture"

[context.branch-deploy.environment]
HUGO_VERSION = "0.108.0"
HUGO_ENV = "production"
