[build]
publish = "public"
command = "hugo"

[context.production]

[context.production.environment]
HUGO_VERSION = "0.74.1"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --buildFuture"

[context.deploy-preview.environment]
HUGO_VERSION = "0.74.1"
HUGO_ENV = "production"

[context.branch-deploy]
command = "hugo --buildFuture"

[context.branch-deploy.environment]
HUGO_VERSION = "0.74.1"
HUGO_ENV = "production"
